#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "error: the PYFILE variable is not set"
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "error: the PYFILE file does not exist"
    exit 1
fi

python3 "$PYFILE"
